<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Bonnie Lin and Nicholas Horton (nhorton@amherst.edu)" />

<meta name="date" content="2018-07-18" />

<title>IPS9 in R: Looking at Data – Distributions (Chapter 1)</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Chapters
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="ch01.pdf">Chapter 1</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    R code
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Chapter01.html">Chapter 1</a>
    </li>
    <li>
      <a href="Chapter02.html">Chapter 2</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Homework
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="hw1.pdf">HW 1</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Solution
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">HW 1</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Clicker Questions
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="clicker01.pdf">Chapter 1</a>
    </li>
  </ul>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="../math3316-fa18.html">
    <span class="glyphicon glyphicon-chevron-up"></span>
     
  </a>
</li>
<li>
  <a href="../math3316-fa18.html">
    <span class="glyphicon glyphicon-home"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">IPS9 in R: Looking at Data – Distributions (Chapter 1)</h1>
<h4 class="author">Bonnie Lin and Nicholas Horton (<a href="mailto:nhorton@amherst.edu" class="email">nhorton@amherst.edu</a>)</h4>
<h4 class="date">July 18, 2018</h4>

</div>

<div id="TOC">
<ul>
<li><a href="#introduction-and-background">Introduction and background</a></li>
<li><a href="#chapter-1-looking-at-data-distributions">Chapter 1: Looking at data – distributions</a><ul>
<li><a href="#section-1.1-data">Section 1.1: Data</a></li>
<li><a href="#section-1.2-displaying-distributions-with-graphs">Section 1.2: Displaying distributions with graphs</a></li>
<li><a href="#section-1.3-describing-distributions-with-numbers">Section 1.3: Describing Distributions with Numbers</a></li>
<li><a href="#section-1.4-density-curves-and-normal-distributions">Section 1.4: Density Curves and Normal Distributions</a></li>
</ul></li>
</ul>
</div>

<div id="introduction-and-background" class="section level2">
<h2>Introduction and background</h2>
<p>These documents are intended to help describe how to undertake analyses introduced as examples in the Ninth Edition of  (2017) by Moore, McCabe, and Craig.</p>
<p>More information about the book can be found <a href="https://macmillanlearning.com/Catalog/product/introductiontothepracticeofstatistics-ninthedition-moore">here</a>. The data used in these documents can be found under Data Sets in the <a href="https://www.macmillanlearning.com/catalog/studentresources/ips9e?_ga=2.29224888.526668012.1531487989-1209447309.1529940008#">Student Site</a>. This file as well as the associated R Markdown reproducible analysis source file used to create it can be found at <a href="https://nhorton.people.amherst.edu/ips9/" class="uri">https://nhorton.people.amherst.edu/ips9/</a>.</p>
<p>This work leverages initiatives undertaken by Project MOSAIC (<a href="http://www.mosaic-web.org" class="uri">http://www.mosaic-web.org</a>), an NSF-funded effort to improve the teaching of statistics, calculus, science and computing in the undergraduate curriculum. In particular, we utilize the <code>mosaic</code> package, which was written to simplify the use of R for introductory statistics courses. A short summary of the R needed to teach introductory statistics can be found in the mosaic package vignettes (<a href="http://cran.r-project.org/web/packages/mosaic" class="uri">http://cran.r-project.org/web/packages/mosaic</a>). A paper describing the mosaic approach was published in the <em>R Journal</em>: <a href="https://journal.r-project.org/archive/2017/RJ-2017-024" class="uri">https://journal.r-project.org/archive/2017/RJ-2017-024</a>.</p>
</div>
<div id="chapter-1-looking-at-data-distributions" class="section level2">
<h2>Chapter 1: Looking at data – distributions</h2>
<p>This file replicates the analyses from Chapter 1: Looking at Data (Distributions).</p>
<p>First, load the packages that will be needed for this document:</p>
<pre class="r"><code>library(mosaic)
library(readr)</code></pre>
<div id="section-1.1-data" class="section level3">
<h3>Section 1.1: Data</h3>
</div>
<div id="section-1.2-displaying-distributions-with-graphs" class="section level3">
<h3>Section 1.2: Displaying distributions with graphs</h3>
<p>The table on page 9 displays the counts of preferences for online resources of 552 first-year college students. We begin by reading the data:</p>
<pre class="r"><code>Online &lt;-
  read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-07ONLINE.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   Source = col_character(),
##   Count = col_double()
## )</code></pre>
<pre class="r"><code>Online</code></pre>
<pre><code>## # A tibble: 4 x 2
##   Source    Count
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 Google      406
## 2 Library      75
## 3 Wikipedia    52
## 4 Other        19</code></pre>
<pre class="r"><code>Online_data &lt;- data.frame(Source = c(rep(&quot;Google&quot;, 406), rep(&quot;Library&quot;, 75),
                                     rep(&quot;Wikipedia&quot;, 52), rep(&quot;Other&quot;, 19)))

tally(~ Online_data, margins = TRUE)</code></pre>
<pre><code>## Online_data
##    Google   Library     Other Wikipedia     Total 
##       406        75        19        52       552</code></pre>
<p>By default, the <code>read_csv()</code> function will output the types of columns, as we see above. To improve readability for future coding, we will suppress the “Parsed with column specification” message by adding <code>message = FALSE</code> at the top of the code chunks.</p>
<p>Since the <code>Online</code> data already have the counts for the sources, we could not demonstrate the <code>tally()</code> function with them. Thus, we created a dataset called <code>Online_data</code> by repeating the sources with the <code>rep()</code> function. We specified the number of repetitions to match the counts in <code>Online</code>. The <code>tally()</code> then counts up the number of observations for each source, while the <code>margins</code> argument, set to TRUE, includes the total number of observations for all sources.</p>
<p>The table on page 10 shows the preference percents. We can also represent the data in percentages, by typing the following:</p>
<pre class="r"><code>options(digits = 2)
tally(~ Online_data, format = &quot;percent&quot;, margins = TRUE)</code></pre>
<pre><code>## Online_data
##    Google   Library     Other Wikipedia     Total 
##      73.6      13.6       3.4       9.4     100.0</code></pre>
<p>We added the <code>format</code> argument to the <code>tally()</code> function to show the data in percentages, and, with the <code>options()</code> function, we controlled the number of digits after the decimal.</p>
<p>Figure 1.2 (page 10) displays the online resource preference data from the above example using a histogram, which we can make by typing:</p>
<pre class="r"><code>gf_histogram(~ Source, data = Online_data, stat = &quot;count&quot;)</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-9-1.png" width="480" /></p>
<pre class="r"><code>gf_histogram(~ forcats::fct_infreq(Source), data = Online_data, stat = &quot;count&quot;) %&gt;%
  gf_labs(x = &quot;Source&quot;)</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-9-2.png" width="480" /></p>
<p>As you can see from the first plot, R orders the x-axis alphabetically, placing “Other” before “Wikipedia”.</p>
<p>However, we can make slight modifications by using the <code>fct_infreq()</code> function in the <code>forcats</code> package. We use the <code>package::function()</code> template to call usefful functions from specific packages without calling the entire package. This function orders the sources, a categorical variable, by frequency. The output now matches the graph on page 10 and graphs the sources on a descending order of count.</p>
<p>Figure 1.3 (page 11) displays the online resource preference data in a pie chart. You can create a simple one using the <code>ggplot2</code> package, which is called with the <code>mosaic</code> package. However, it is worth noting that the R documentation does not generally recommend pie charts as their features are somewhat limited.</p>
<pre class="r"><code> Online_Percent &lt;-
   read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-08ONLINE.csv&quot;)

Online_Percent &lt;- Online %&gt;%
  mutate(Count = 100 * Count/sum(Count)) %&gt;%
  rename(Percent = Count)

Preferences &lt;- ggplot(Online_Percent, aes(x = &quot;&quot;, y = Percent, fill = factor(Source))) +
  geom_bar(width = 1, stat = &quot;identity&quot;)
Preferences + coord_polar(theta=&quot;y&quot;) + labs(fill = &quot;Source&quot;) +  theme_void()</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-10-1.png" width="480" /></p>
<p>The <code>coord_polar()</code> function converts stacked bar charts into the polar coordinate system to make pie charts.</p>
<p>Below is the code that generates the stem and leaf plot (page 12) that displays the effect of SCF on the absorption of calcium in adolescent boys and girls:</p>
<pre class="r"><code>SCF &lt;- read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-11SCF.csv&quot;)
SCF_Treatment &lt;- SCF %&gt;%
  filter(Treatment == &quot;SCF&quot;)
with(data = SCF_Treatment, stem(Absorption))</code></pre>
<pre><code>## 
##   The decimal point is 1 digit(s) to the right of the |
## 
##   3 | 15
##   4 | 2333445789
##   5 | 003349
##   6 | 12
##   7 | 036</code></pre>
<p>Since the data include absorption percentages of the control participants, we use the <code>filter()</code> function to isolate the boys and girls who consumed 12 grams per day of SCF from the control group. Once we have defined this subgroup, we can create a stemplot with the <code>with()</code> function, in which the arguments require the data and the expression <code>stem()</code>. This calls the variable <code>Absorption</code> within the <code>SCF_Treatment</code> data is and displays the vector as a stem-and-leaf plot.</p>
<p>Figure 1.7 (page 15) shows the IQ scores of 60 fifth-grade students chosen at random from one school. The data first need to be divided into classes or levels of equal width. We can then count the number of individuals in each class/level and use these counts to create a histogram.</p>
<pre class="r"><code>IQ &lt;-
  read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-14IQ.csv&quot;)
levels &lt;- c(75, 85, 95, 105, 115, 125, 135, 145, 155)
labels &lt;- as.factor(seq(from = 80, to = 150, by = 10))
IQ_Count &lt;- IQ %&gt;%
  mutate(Class = cut(IQ, levels, labels = labels))
gf_bar(~ Class, data = IQ_Count)</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-14-1.png" width="480" /></p>
<p>The <code>cut()</code> function divides the IQ dataset into the defined levels and assigns the values into the appropriate categories. By setting the <code>stat</code> argument in the <code>gf_histogram()</code> function to “count”, we can create a histogram for discrete variables. The distribution of scores on IQ tests is roughly “bell-shaped”.</p>
<p>Table 1.2 (page 17) displays the lengths of the first 80 calls. To call the first 80 observations in the dataset, we can use the <code>head()</code> function and specify the number of observations.</p>
<pre class="r"><code>Customer_Calls &lt;-
  read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-16CALLS.csv&quot;)
head(Customer_Calls, 80)</code></pre>
<pre><code>## # A tibble: 80 x 1
##    length
##     &lt;dbl&gt;
##  1     77
##  2    289
##  3    128
##  4     59
##  5     19
##  6    148
##  7    157
##  8    203
##  9    126
## 10    118
## # … with 70 more rows</code></pre>
<p>Figure 1.8 displays the histogram of the lengths of all 31,492 calls. To exclude the few lengths that are greater than 1200 seconds (20 minutes), we can use the <code>filter()</code> function.</p>
<pre class="r"><code>Customer_Calls %&gt;%
  filter(length &lt;= 1200) %&gt;%
  gf_histogram(~ length, binwidth = 5) %&gt;%
  gf_labs(x = &quot;Service time (seconds)&quot;, y = &quot;Count of calls&quot;)</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-16-1.png" width="480" /></p>
<p>From the last visual, we can assess the shape of the distribution of IQ scores. We can also use the <code>favstats()</code> function to find the center and spread:</p>
<pre class="r"><code>favstats(~ IQ, data = IQ)</code></pre>
<pre><code>##  min  Q1 median  Q3 max mean sd  n missing
##   81 104    114 125 145  115 15 60       0</code></pre>
<p>We see that the median IQ score is 114 points and that the data spread from 81 to 145 points. Both the distribution as well as the summary statistics point to a symmetric, unimodal pattern in the IQ data.</p>
<p>On the other hand, the distribution of call lengths displayed above is strongly <em>skewed to the right.</em> We can run the <code>favstats()</code> function to find exact values of the center and spread:</p>
<pre class="r"><code>favstats(~ length, data = Customer_Calls)</code></pre>
<pre><code>##  min Q1 median  Q3   max mean  sd     n missing
##    1 57    115 225 28739  189 313 31492       0</code></pre>
<p>We can say that the length of a typical call is about the median value of the dataset, or 115 seconds. The data spread very widely, spanning from 1 second to 28, 739 seconds. The outliers were omitted from the histogram above, but it is still clear thats the shape of the distribution is hardly symmetric.</p>
<p>Next, we will look at the number of undergraduate college students in each of the states. Here, we have loaded in the data and displayed the data in a histogram. See Figure 1.9 (page 20):</p>
<pre class="r"><code>College &lt;-
  read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-19COLLEGE.csv&quot;)
gf_dhistogram(~ Undergrads, data = College)</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-19-1.png" width="480" /></p>
<pre class="r"><code>College %&gt;%
  filter(Undergrads == max(Undergrads))</code></pre>
<pre><code>## # A tibble: 1 x 4
##   State      Undergrads Population UGradPerThou
##   &lt;chr&gt;           &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;
## 1 California    2172354   36121296         60.1</code></pre>
<p>California is the outlier in this case, by having 2,687,893 undergraduate students.</p>
<p>The <em>UGradPerThou</em> variable in the dataset takes into account the variation in state populations and expresses the number of undergraduate students per 1000 people in each state. Below is a stemplot, which provides essentially the same information as a histogram with the added benefit of being able to easily extract indiviudal data points.</p>
<pre class="r"><code>with(College, stem(UGradPerThou))</code></pre>
<pre><code>## 
##   The decimal point is 1 digit(s) to the right of the |
## 
##   3 | 8
##   4 | 1111133
##   4 | 55556667777788889
##   5 | 001112224444
##   5 | 566
##   6 | 00001
##   6 | 79
##   7 | 12
##   7 | 7</code></pre>
<pre class="r"><code>College %&gt;%
  filter(UGradPerThou &gt; 76)</code></pre>
<pre><code>## # A tibble: 1 x 4
##   State   Undergrads Population UGradPerThou
##   &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;
## 1 Arizona     476547    6178251         77.1</code></pre>
<p>To interpret this plot alongside the histogram, we can take California for example. California has 60 undergraduate students per 1000 people, making it one of the higher values, though certainly not the highest. Though the last histogram established California as an outlier for its extremely large number of undergraduate students, the stemplot points out another state as an outlier for having the largest proportion of undergraduate students.</p>
<p>Since we can view individual points in stemplots, we can use the <code>filter()</code> function to find the name of the outlier state, which turns out to be Arizona, with a ratio of 77.1 undergraduate students per 1000 people in the state.</p>
<p>Below is the code that we use to create a stemplot of the values of parathyroid hormone levels (PTH) measured on a sample of 29 boys and girls aged 12 to 15 years (Figure 1.11 on page 21):</p>
<pre class="r"><code>PTH &lt;- read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-21PTH.csv&quot;)
with(PTH, stem(PTH))</code></pre>
<pre><code>## 
##   The decimal point is 1 digit(s) to the right of the |
## 
##    0 | 9
##    2 | 5888901113589
##    4 | 0568990099
##    6 | 3411
##    8 | 
##   10 | 
##   12 | 7</code></pre>
<p>The 127 PTH value at the base of the stemplot stands out as the outlier.</p>
<p>Following is an example of a plot that displays observations in time order. The serum levels of vitamin have been plotted against time of year for samples of subjects from Switzerland (see Figure 1.12 on page 22).</p>
<pre class="r"><code>VITDS &lt;-
  read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-22VITDS.csv&quot;)
gf_point(VitaminD ~ Months, data = VITDS) %&gt;%
  gf_smooth(se = FALSE) %&gt;%
  gf_labs(x = &quot;Months&quot;, y= &quot;Vitamin D(nmol/1)&quot;)</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-22-1.png" width="480" /></p>
<p>By default, the <code>se</code> argument in <code>gf_smooth()</code> function is set to TRUE, so we set it to FALSE to suppress the confidence intervals.</p>
</div>
<div id="section-1.3-describing-distributions-with-numbers" class="section level3">
<h3>Section 1.3: Describing Distributions with Numbers</h3>
<p>Like the previous examples of stemplots, you can type the following to display the data collected on the time, in days, that businesses took to complete all of the starting procedures (page 29):</p>
<pre class="r"><code>TTS24 &lt;- read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-23TTS24.csv&quot;)
with(TTS24, stem(Time, scale = 2))</code></pre>
<pre><code>## 
##   The decimal point is 1 digit(s) to the right of the |
## 
##   0 | 2455556678
##   1 | 01236799
##   2 | 45
##   3 | 28
##   4 | 9
##   5 | 3</code></pre>
<p>We can control the length of the stemplot by changing the <code>scale</code> argument from 1, which is the default setting, to 2.</p>
<p>Other than using the <code>favstats()</code> function to calculate summary statistics, we can also use the <code>mean()</code> function to find this specific statistic.</p>
<pre class="r"><code>mean(~ Time, data = TTS24)</code></pre>
<pre><code>## [1] 16</code></pre>
<p>Similarly, we can use the <code>median()</code> function to find this specific statistic (page 31):</p>
<pre class="r"><code>median(~ Time, data = TTS24)</code></pre>
<pre><code>## [1] 12</code></pre>
<p>You can use the stemplot above to confirm the median value.</p>
<p>Other functions that operate similarly include:</p>
<ul>
<li>range(): to find the maximum and minimum values</li>
<li>IRQ(): to calculate the quartiles (Q3 - Q1)</li>
</ul>
<p>You can type either line of code to get the help file for the function to see more information:</p>
<pre class="r"><code>?favstats
favstats()</code></pre>
<p>Figure 1.15 (page 37) displays side-by-side boxplots for age of the death of writers in the three categories. of literature.</p>
<pre class="r"><code>POETS &lt;- read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-31POETS.csv&quot;)
gf_boxplot(Age ~ Type, data = POETS)</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-31-1.png" width="480" /></p>
<p>To demonstrate how to linearly transform vectors, we will use the homework scores and the corresponding final grade points for five students (page 45):</p>
<pre class="r"><code>Score &lt;- c(1056, 1080, 900, 1164, 1020)
Points &lt;- Score/4
mean(Score)/mean(Points)</code></pre>
<pre><code>## [1] 4</code></pre>
<p>We create a vector called <code>Score</code> that holds the total score of the 12 homework assignments. We can convert the homework scores to final grade points by dividing each value in the <code>Score</code> vector by 4. Because this is a linear transformation, the mean of the summed homework score is just four times the mean of the points.</p>
<p>Figure 1.20(a) (page 52) shows the distribution of the time it takes to start a business, as a density plot overlain a histogram. We can recreate this by typing:</p>
<pre class="r"><code>TTS &lt;- read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-36TITANIC.csv&quot;)
gf_histogram( ~ Time, data = TTS, binwidth = 20, center = 10) %&gt;%
  gf_dens()</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-36-1.png" width="480" /></p>
<p>Note that we are using the data as named and provided by the publishers.</p>
</div>
<div id="section-1.4-density-curves-and-normal-distributions" class="section level3">
<h3>Section 1.4: Density Curves and Normal Distributions</h3>
<p>Figure 1.30 (page 67) is a Normal quantile plot of the 60 fifth-grade IQ scores from page 14. We can recreate the plot here:</p>
<pre class="r"><code>IQ &lt;- read_csv(&quot;https://nhorton.people.amherst.edu/ips9/data/chapter01/EG01-46IQ.csv&quot;)
gf_qq(~ IQ, data = IQ) %&gt;%
  gf_qqline(linetype = &quot;solid&quot;, color = &quot;red&quot;) %&gt;%
  gf_labs(x = &quot;Normal Score&quot;, y = &quot;IQ&quot;)</code></pre>
<p><img src="Chapter01_files/figure-html/eg1-46-1.png" width="480" /></p>
<p>Since the points do not deviate far from the straight line drawn on the plot, we can conclude that the distribution of the IQ data is approximately Normal. Here, we use the <code>gf_qq()</code> function to plot the points and then add the <code>gf_qqline()</code> function, with the correct specifications, to overlay the straight diagonal line.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
