((nil . ((indent-tabs-mode . nil)
         ;; (fill-column . 70)
         (sentence-end-double-space . t)))
 (org-mode . ((mode . auto-fill)
              ;; (org-hugo-section . "dir-locals-test")
              ;; (org-hugo-front-matter-format . "yaml")
              ;; (org-hugo-footer . "\n\nThis text is auto inserted at the end of the exported Markdown.")
              (org-hugo-preserve-filling . nil)
              (org-hugo-use-code-for-kbd . t)
              (org-hugo-export-with-toc . t)
              (org-hugo-export-with-section-numbers . t)
              (org-hugo-export-creator-string . "Emacs 26.1 (Org mode 9.1.14 + ox-hugo")
              ;; (org-hugo-date-format . "%Y-%m-%d")
              ;; (org-hugo-auto-export-on-save . t)
              )))
